/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.userRoles;
import Organizations.OrganizationDirectory;
import enterprise.Bodies.BrokerageFirm;
import enterprise.Bodies.Enterprise;
import enterprise.Bodies.EnterpriseDirectory;
import enterprise.Bodies.InvestmentAdvisoryFirm;
import enterprise.Bodies.RegulatoryBody;
import enterprise.Bodies.BrokerageFirm;
import enterprise.Bodies.InvestmentAdvisoryFirm;
import enterprise.Bodies.RegulatoryBody;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.Person;
import ui.Admin.Admin;
import ui.Admin.PasswordDirectory;
import ui.Admin.PersonDirectory;
/**
 *
 * @author rohanjauhari
 */
public class EnterpriseAdmin extends javax.swing.JPanel {

    /**
     * Creates new form EnterpriseAdmin
     */
//    OrganizationDirectory organizationDirectoryBF, organizationDirectoryIAF,organizationDirectoryRB,organizationDirectorySE;
    EnterpriseDirectory enterpriseDirectory;
    Admin admin;
    JPanel userProcessContainer;
    PasswordDirectory passwordDirectory;
    PersonDirectory personDirectory;


    String enterprise="";
    OrganizationDirectory organizationDirectoryBF, organizationDirectoryIAF, organizationDirectoryRB,organizationDirectorySE;
    public EnterpriseAdmin(JPanel userProcessContainer, EnterpriseDirectory enterpriseDirectory, Admin admin, OrganizationDirectory organizationDirectoryBF, OrganizationDirectory organizationDirectoryIAF,OrganizationDirectory organizationDirectoryRB, OrganizationDirectory organizationDirectorySE) {
        initComponents();
        this.organizationDirectoryBF = organizationDirectoryBF;
        this.organizationDirectoryIAF = organizationDirectoryIAF;
        this.organizationDirectoryRB = organizationDirectoryRB;
        this.organizationDirectorySE = organizationDirectorySE;
        this.admin = admin;
        this.userProcessContainer = userProcessContainer;
        this.enterpriseDirectory =  enterpriseDirectory;
        for (Enterprise e:enterpriseDirectory.getEnterprices())
            enterpriseAdmins.addItem(e.getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLogin1 = new javax.swing.JButton();
        enterpriseAdmins = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        txtPass = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();

        btnLogin1.setBackground(new java.awt.Color(204, 176, 255));
        btnLogin1.setFont(new java.awt.Font("Microsoft New Tai Lue", 3, 14)); // NOI18N
        btnLogin1.setText("Login");
        btnLogin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogin1ActionPerformed(evt);
            }
        });

        setBackground(new java.awt.Color(153, 137, 202));
        setPreferredSize(new java.awt.Dimension(720, 550));

        enterpriseAdmins.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None" }));
        enterpriseAdmins.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterpriseAdminsActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Microsoft New Tai Lue", 3, 14)); // NOI18N
        jLabel1.setText("Enterprise");

        jButton1.setBackground(new java.awt.Color(151, 98, 255));
        jButton1.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Enterprise Admin Login");
        jButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Microsoft New Tai Lue", 3, 14)); // NOI18N
        jLabel6.setText("Username:");

        jLabel5.setFont(new java.awt.Font("Microsoft New Tai Lue", 3, 14)); // NOI18N
        jLabel5.setText("Password:");

        txtUsername.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 24)); // NOI18N
        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });

        txtPass.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 24)); // NOI18N
        txtPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPassActionPerformed(evt);
            }
        });

        btnLogin.setBackground(new java.awt.Color(204, 176, 255));
        btnLogin.setFont(new java.awt.Font("Microsoft New Tai Lue", 3, 14)); // NOI18N
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(84, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 552, Short.MAX_VALUE)
                .addContainerGap(84, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLogin))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(307, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtUsername)
                            .addComponent(txtPass)
                            .addComponent(enterpriseAdmins, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(214, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(108, 108, 108)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(enterpriseAdmins, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(btnLogin)
                .addContainerGap(153, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void enterpriseAdminsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterpriseAdminsActionPerformed
        // TODO add your handling code here:
        enterprise = enterpriseAdmins.getSelectedItem().toString();
    }//GEN-LAST:event_enterpriseAdminsActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void txtPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPassActionPerformed

    private void btnLogin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogin1ActionPerformed
        // TODO add your handling code here:
        Person validatePassword;
        System.out.println(txtPass.getText());
        validatePassword = admin.validatePassword(txtUsername.getText(), txtPass.getText());
        if (validatePassword==null){
            JOptionPane.showMessageDialog(this, "Sign in failed!");
            return;
        }
        Admin d = new Admin(userProcessContainer,passwordDirectory, personDirectory, enterpriseDirectory);
        userProcessContainer.add("Dashboard", d);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnLogin1ActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        Person validatePassword;
        System.out.println(txtPass.getText());
        validatePassword = admin.validatePassword(txtUsername.getText(), txtPass.getText());
        if (validatePassword==null){
            JOptionPane.showMessageDialog(this, "Sign in failed!");
            return;
        }
        Admin d = new Admin(userProcessContainer,passwordDirectory, personDirectory, enterpriseDirectory);
        userProcessContainer.add("Dashboard", d);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnLoginActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnLogin1;
    private javax.swing.JComboBox<String> enterpriseAdmins;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
