/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.userRoles;
import Organizations.OrganizationDirectory;
import enterprise.Bodies.BrokerageFirm;
import enterprise.Bodies.Enterprise;
import enterprise.Bodies.EnterpriseDirectory;
import enterprise.Bodies.InvestmentAdvisoryFirm;
import enterprise.Bodies.RegulatoryBody;
import enterprise.Bodies.BrokerageFirm;
import enterprise.Bodies.InvestmentAdvisoryFirm;
import enterprise.Bodies.RegulatoryBody;
import java.awt.CardLayout;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.Person;
import ui.Admin.Admin;
import ui.Admin.StockExchange;
/**
 *
 * @author rohanjauhari
 */
public class EnterpriseAdmin extends javax.swing.JPanel {

    /**
     * Creates new form EnterpriseAdmin
     */
//    OrganizationDirectory organizationDirectoryBF, organizationDirectoryIAF,organizationDirectoryRB,organizationDirectorySE;
    EnterpriseDirectory enterpriseDirectory;
    Admin admin;
    JPanel userProcessContainer;
    String enterprise="";
    OrganizationDirectory organizationDirectoryBF, organizationDirectoryIAF, organizationDirectoryRB,organizationDirectorySE;
    public EnterpriseAdmin(JPanel userProcessContainer, EnterpriseDirectory enterpriseDirectory, Admin admin, OrganizationDirectory organizationDirectoryBF, OrganizationDirectory organizationDirectoryIAF,OrganizationDirectory organizationDirectoryRB, OrganizationDirectory organizationDirectorySE) {
        initComponents();
        this.organizationDirectoryBF = organizationDirectoryBF;
        this.organizationDirectoryIAF = organizationDirectoryIAF;
        this.organizationDirectoryRB = organizationDirectoryRB;
        this.organizationDirectorySE = organizationDirectorySE;
        this.admin = admin;
        this.userProcessContainer = userProcessContainer;
        this.enterpriseDirectory =  enterpriseDirectory;
        HashMap<String,Integer> flag = new HashMap<>();
        for (Enterprise e:enterpriseDirectory.getEnterprices()){
            if (flag.get(e.getName())==null)
                enterpriseAdmins.addItem(e.getName());
            flag.put(e.getName(), 1);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        enterpriseAdmins = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        txtPass = new javax.swing.JPasswordField();

        setBackground(new java.awt.Color(204, 204, 255));

        enterpriseAdmins.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None" }));
        enterpriseAdmins.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterpriseAdminsActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Optima", 3, 14)); // NOI18N
        jLabel1.setText("Enterprise");

        jLabel2.setFont(new java.awt.Font("Optima", 3, 14)); // NOI18N
        jLabel2.setText("Password");

        btnLogin.setBackground(new java.awt.Color(102, 255, 255));
        btnLogin.setFont(new java.awt.Font("Optima", 1, 14)); // NOI18N
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Optima", 3, 14)); // NOI18N
        jLabel3.setText("Username");

        jLabel4.setFont(new java.awt.Font("Optima", 3, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 0, 153));
        jLabel4.setText("Enterprise Admin Login");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(180, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(20, 20, 20))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addGap(20, 20, 20)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(enterpriseAdmins, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(167, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLogin)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {enterpriseAdmins, txtPass, txtUsername});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(jLabel4)
                .addGap(84, 84, 84)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enterpriseAdmins, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(247, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void enterpriseAdminsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterpriseAdminsActionPerformed
        // TODO add your handling code here:
        enterprise = enterpriseAdmins.getSelectedItem().toString();
    }//GEN-LAST:event_enterpriseAdminsActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        Person p = admin.validatePassword(txtUsername.getText() ,txtPass.getText(),"Enterprise Admin");
        
        if (p!=null){
            if (p.getEnterpriseName()!=enterprise || p.getDesignation()!="Enterprise Admin")
            {
                JOptionPane.showMessageDialog(this, "Sign in failed!");
                return;
            }
            if (enterprise=="Brokerage Firm"){
                BrokerageFirm bf = new BrokerageFirm(userProcessContainer, enterprise,organizationDirectoryBF,admin,txtUsername.getText(),p);
                userProcessContainer.add("BrokerageFirm", bf);
                CardLayout layout = (CardLayout)userProcessContainer.getLayout();
                layout.next(userProcessContainer);
            }
            if (enterprise=="Investment Advisory"){
                InvestmentAdvisoryFirm iaf = new InvestmentAdvisoryFirm(userProcessContainer,enterprise,organizationDirectoryIAF,admin,txtUsername.getText());
                userProcessContainer.add("InvestmentAdvisoryFirm", iaf);
                CardLayout layout = (CardLayout)userProcessContainer.getLayout();
                layout.next(userProcessContainer);
            }
            if (enterprise=="Regulatory Body"){
                RegulatoryBody rb = new RegulatoryBody(userProcessContainer,enterprise,organizationDirectoryRB,admin,txtUsername.getText());
                userProcessContainer.add("RegulatoryBody", rb);
                CardLayout layout = (CardLayout)userProcessContainer.getLayout();
                layout.next(userProcessContainer);
            }
            if (enterprise=="Stock Exchange"){
                StockExchange bf = new StockExchange(userProcessContainer,enterprise,organizationDirectorySE,admin,txtUsername.getText(), p);
                userProcessContainer.add("StockExchange", bf);
                CardLayout layout = (CardLayout)userProcessContainer.getLayout();
                layout.next(userProcessContainer);
            }
        }
        else
            JOptionPane.showMessageDialog(this, "Sign in failed!");
    }//GEN-LAST:event_btnLoginActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JComboBox<String> enterpriseAdmins;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
