/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.userRoles;

import Organizations.AdvisoryTeam;
import Organizations.ComplianceTeam;
import Organizations.CustomerSupportTeam;
import Organizations.ITDepartment;
import Organizations.Organization;
import Organizations.OrganizationDirectory;
import Organizations.RiskManagementTeam;
import Organizations.TradingDepartment;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import ui.Admin.Admin;
import ui.Roles.RoleDirectory;
/**
 *
 * @author rohanjauhari
 */
public class OrganizationAdmin extends javax.swing.JPanel {

    /**
     * Creates new form OrganizationAdmin
     */
    JPanel userProcessContainer;
    String organization;
//    OrganizationDirectory userDirectoryITD,userDirectoryTD,userDirectoryCT,userDirectoryAT;
    Admin admin;
    RoleDirectory roleDirectoryITD,roleDirectoryTD,roleDirectoryCT,roleDirectoryAT,roleDirectoryCST,roleDirectoryRMT;
    public OrganizationAdmin(JPanel userProcessContainer, RoleDirectory roleDirectoryITD,RoleDirectory roleDirectoryTD,RoleDirectory roleDirectoryCT,RoleDirectory roleDirectoryAT,RoleDirectory roleDirectoryCST,RoleDirectory roleDirectoryRMT,OrganizationDirectory organizationDirectoryBF, OrganizationDirectory organizationDirectoryIAF, OrganizationDirectory organizationDirectoryRB, OrganizationDirectory organizationDirectorySE, Admin admin) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.admin = admin;
        this.roleDirectoryITD=roleDirectoryITD;
        this.roleDirectoryCT=roleDirectoryCT;
        this.roleDirectoryAT=roleDirectoryAT;
        this.roleDirectoryCST=roleDirectoryCST;
        this.roleDirectoryRMT=roleDirectoryRMT;
        this.roleDirectoryTD=roleDirectoryTD;
        ArrayList<Organization> organizationDirectory = new ArrayList();
        organizationDirectory.addAll(organizationDirectoryBF.getOrganizations());
        organizationDirectory.addAll(organizationDirectoryIAF.getOrganizations());
        organizationDirectory.addAll(organizationDirectoryRB.getOrganizations());
        organizationDirectory.addAll(organizationDirectorySE.getOrganizations());
        for (Organization o:organizationDirectory)
            cmbOrg.addItem(o.getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        cmbOrg = new javax.swing.JComboBox<>();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 137, 202));

        jButton1.setBackground(new java.awt.Color(151, 98, 255));
        jButton1.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Organization Admin Login");
        jButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        cmbOrg.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None" }));
        cmbOrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbOrgActionPerformed(evt);
            }
        });

        txtUsername.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 24)); // NOI18N
        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });

        txtPassword.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 24)); // NOI18N
        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Microsoft New Tai Lue", 3, 14)); // NOI18N
        jLabel4.setText("Organization:");

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Microsoft New Tai Lue", 3, 14)); // NOI18N
        jLabel6.setText("Username:");

        jLabel5.setFont(new java.awt.Font("Microsoft New Tai Lue", 3, 14)); // NOI18N
        jLabel5.setText("Password:");

        btnLogin.setBackground(new java.awt.Color(204, 176, 255));
        btnLogin.setFont(new java.awt.Font("Microsoft New Tai Lue", 3, 14)); // NOI18N
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(150, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnLogin)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, 0)
                                .addComponent(cmbOrg, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 150, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbOrg, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(btnLogin)
                .addContainerGap(257, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cmbOrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbOrgActionPerformed
        // TODO add your handling code here:
        organization = cmbOrg.getSelectedItem().toString();
    }//GEN-LAST:event_cmbOrgActionPerformed

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
       if (admin.validatePassword(txtUsername.getText() ,txtPassword.getText())!=null){
            if (organization=="IT Department"){
                ITDepartment bf = new ITDepartment(userProcessContainer, organization, roleDirectoryITD, admin,txtUsername.getText());
                userProcessContainer.add("ITDepartment", bf);
                CardLayout layout = (CardLayout)userProcessContainer.getLayout();
                layout.next(userProcessContainer);
            }
            if (organization=="Trading Department"){
                TradingDepartment iaf = new TradingDepartment(userProcessContainer, organization, roleDirectoryTD, admin,txtUsername.getText());
                userProcessContainer.add("TradingDepartment", iaf);
                CardLayout layout = (CardLayout)userProcessContainer.getLayout();
                layout.next(userProcessContainer);
            }
            if (organization=="Compliance Team"){
                ComplianceTeam rb = new ComplianceTeam(userProcessContainer, organization, roleDirectoryCT, admin,txtUsername.getText());
                userProcessContainer.add("ComplianceTeam", rb);
                CardLayout layout = (CardLayout)userProcessContainer.getLayout();
                layout.next(userProcessContainer);
            }
            if (organization=="Advisory Team"){
                AdvisoryTeam bf = new AdvisoryTeam(userProcessContainer, organization, roleDirectoryAT, admin,txtUsername.getText());
                userProcessContainer.add("AdvisoryTeam", bf);
                CardLayout layout = (CardLayout)userProcessContainer.getLayout();
                layout.next(userProcessContainer);
            }
            if (organization=="Customer Support Team"){
                CustomerSupportTeam bf = new CustomerSupportTeam(userProcessContainer,organization,roleDirectoryCST, admin,txtUsername.getText());
                userProcessContainer.add("StockExchange", bf);
                CardLayout layout = (CardLayout)userProcessContainer.getLayout();
                layout.next(userProcessContainer);
            }
            if (organization=="Risk Management Team"){
                RiskManagementTeam rmf = new RiskManagementTeam(userProcessContainer,organization,roleDirectoryRMT, admin,txtUsername.getText());
                userProcessContainer.add("StockExchange", rmf);
                CardLayout layout = (CardLayout)userProcessContainer.getLayout();
                layout.next(userProcessContainer);
            }
        }
        else
            JOptionPane.showMessageDialog(this, "Sign in failed!");
    }//GEN-LAST:event_btnLoginActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JComboBox<String> cmbOrg;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
