/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.userRoles;

import Organizations.AdvisoryTeam;
import Organizations.ComplianceTeam;
import ui.Admin.CustomerSupportTeam;
import Organizations.ITDepartment;
import Organizations.Organization;
import Organizations.OrganizationDirectory;
import Organizations.RiskManagementTeam;
import Organizations.TradingDepartment;
import enterprise.Bodies.Enterprise;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.Person;
import ui.Admin.Admin;
import ui.Roles.RoleDirectory;
/**
 *
 * @author rohanjauhari
 */
public class OrganizationAdmin extends javax.swing.JPanel {

    /**
     * Creates new form OrganizationAdmin
     */
    JPanel userProcessContainer;
    String organization;
//    OrganizationDirectory userDirectoryITD,userDirectoryTD,userDirectoryCT,userDirectoryAT;
    Admin admin;
    RoleDirectory roleDirectoryITD,roleDirectoryTD,roleDirectoryCT,roleDirectoryAT,roleDirectoryCST,roleDirectoryRMT;
    public OrganizationAdmin(JPanel userProcessContainer, RoleDirectory roleDirectoryITD,RoleDirectory roleDirectoryTD,RoleDirectory roleDirectoryCT,RoleDirectory roleDirectoryAT,RoleDirectory roleDirectoryCST,RoleDirectory roleDirectoryRMT,OrganizationDirectory organizationDirectoryBF, OrganizationDirectory organizationDirectoryIAF, OrganizationDirectory organizationDirectoryRB, OrganizationDirectory organizationDirectorySE, Admin admin) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.admin = admin;
        this.roleDirectoryITD=roleDirectoryITD;
        this.roleDirectoryCT=roleDirectoryCT;
        this.roleDirectoryAT=roleDirectoryAT;
        this.roleDirectoryCST=roleDirectoryCST;
        this.roleDirectoryRMT=roleDirectoryRMT;
        this.roleDirectoryTD=roleDirectoryTD;
        ArrayList<Organization> organizationDirectory = new ArrayList();
        organizationDirectory.addAll(organizationDirectoryBF.getOrganizations());
        organizationDirectory.addAll(organizationDirectoryIAF.getOrganizations());
        organizationDirectory.addAll(organizationDirectoryRB.getOrganizations());
        organizationDirectory.addAll(organizationDirectorySE.getOrganizations());
        HashMap<String,Integer> flag = new HashMap<>();

        for (Organization o:organizationDirectory){
            if (flag.get(o.getName())==null)
                cmbOrg.addItem(o.getName());
            flag.put(o.getName(), 1);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        cmbOrg = new javax.swing.JComboBox<>();
        txtUsername = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();

        jLabel1.setText("Organization:");

        jLabel2.setText("Username");

        jLabel3.setText("Password");

        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        cmbOrg.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None" }));
        cmbOrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbOrgActionPerformed(evt);
            }
        });

        jLabel4.setText("Organization Admin Login");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(235, 235, 235)
                        .addComponent(btnLogin))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(282, 282, 282)
                        .addComponent(jLabel4))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(172, 172, 172)
                            .addComponent(jLabel3)
                            .addGap(18, 18, 18)
                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(152, 152, 152)
                                    .addComponent(jLabel1))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(164, 164, 164)
                                    .addComponent(jLabel2)))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtUsername)
                                .addComponent(cmbOrg, 0, 90, Short.MAX_VALUE)))))
                .addContainerGap(240, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(jLabel4)
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(cmbOrg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(btnLogin)
                .addContainerGap(338, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        Person pp=admin.validatePassword(txtUsername.getText() ,txtPassword.getText(),"Organization Admin");
        if (pp.getOrgName()!=organization || pp.getDesignation()!="Organization Admin"){
            JOptionPane.showMessageDialog(this, "Sign in failed!");
            return;
        }
        if (pp!=null){
            if (organization=="IT Department"){
                ITDepartment bf = new ITDepartment(userProcessContainer, organization, roleDirectoryITD, admin, txtUsername.getText());
                userProcessContainer.add("ITDepartment", bf);
                CardLayout layout = (CardLayout)userProcessContainer.getLayout();
                layout.next(userProcessContainer);
            }
            if (organization=="Trading Department"){
                TradingDepartment iaf = new TradingDepartment(userProcessContainer, organization, roleDirectoryTD, admin, txtUsername.getText());
                userProcessContainer.add("TradingDepartment", iaf);
                CardLayout layout = (CardLayout)userProcessContainer.getLayout();
                layout.next(userProcessContainer);
            }
            if (organization=="Compliance Team"){
                ComplianceTeam rb = new ComplianceTeam(userProcessContainer, organization, roleDirectoryCT, admin, txtUsername.getText());
                userProcessContainer.add("ComplianceTeam", rb);
                CardLayout layout = (CardLayout)userProcessContainer.getLayout();
                layout.next(userProcessContainer);
            }
            if (organization=="Advisory Team"){
                AdvisoryTeam bf = new AdvisoryTeam(userProcessContainer, organization, roleDirectoryAT, admin, txtUsername.getText());
                userProcessContainer.add("AdvisoryTeam", bf);
                CardLayout layout = (CardLayout)userProcessContainer.getLayout();
                layout.next(userProcessContainer);
            }
            if (organization=="Customer Support Team"){
                CustomerSupportTeam bf = new CustomerSupportTeam(userProcessContainer,organization,roleDirectoryCST, admin,txtUsername.getText());
                userProcessContainer.add("CustomerSupportTeam", bf);
                CardLayout layout = (CardLayout)userProcessContainer.getLayout();
                layout.next(userProcessContainer);
            }
            if (organization=="Risk Management Team"){
                RiskManagementTeam rmf = new RiskManagementTeam(userProcessContainer,organization,roleDirectoryRMT, admin,txtUsername.getText());
                userProcessContainer.add("RiskManagementTeam", rmf);
                CardLayout layout = (CardLayout)userProcessContainer.getLayout();
                layout.next(userProcessContainer);
            }
        }
        else
            JOptionPane.showMessageDialog(this, "Sign in failed!");
    }//GEN-LAST:event_btnLoginActionPerformed

    private void cmbOrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbOrgActionPerformed
        // TODO add your handling code here:
        organization = cmbOrg.getSelectedItem().toString();
    }//GEN-LAST:event_cmbOrgActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JComboBox<String> cmbOrg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
