/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.userRoles;

import Organizations.AdvisoryTeam;
import Organizations.ComplianceTeam;
import Organizations.CustomerSupportTeam;
import Organizations.ITDepartment;
import Organizations.Organization;
import Organizations.OrganizationDirectory;
import Organizations.RiskManagementTeam;
import Organizations.TradingDepartment;
import java.awt.CardLayout;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import ui.Admin.Admin;
import ui.Admin.CustomerSupportDashboard;
import ui.Roles.BrokerageManager;
import ui.Roles.ComplianceOfficer;
import ui.Roles.RiskAnalyst;
import ui.Roles.ExchangeAdministrator;
import ui.Roles.FinancialAdvisor;
import ui.Roles.Role;
import ui.Roles.RoleDirectory;
/**
 *
 * @author rohanjauhari
 */
public class RoleLogin extends javax.swing.JPanel {

    /**
     * Creates new form OrganizationAdmin
     */
    JPanel userProcessContainer;
    String role;
//    OrganizationDirectory userDirectoryITD,userDirectoryTD,userDirectoryCT,userDirectoryAT;
    Admin admin;
    public RoleLogin(JPanel userProcessContainer, RoleDirectory roleDirectoryITD,RoleDirectory roleDirectoryTD,RoleDirectory roleDirectoryCT,RoleDirectory roleDirectoryAT,RoleDirectory roleDirectoryCST,RoleDirectory roleDirectoryRMT, Admin admin) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.admin = admin;

        ArrayList<Role> roleDirectory = new ArrayList();
        roleDirectory.addAll(roleDirectoryITD.getRoles());
        roleDirectory.addAll(roleDirectoryTD.getRoles());
        roleDirectory.addAll(roleDirectoryCT.getRoles());
        roleDirectory.addAll(roleDirectoryAT.getRoles());
        roleDirectory.addAll(roleDirectoryCST.getRoles());
        roleDirectory.addAll(roleDirectoryRMT.getRoles());
        for (Role o:roleDirectory)
            cmbRole.addItem(o.getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        cmbRole = new javax.swing.JComboBox<>();
        txtUsername = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();

        setBackground(new java.awt.Color(153, 153, 255));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Microsoft New Tai Lue", 3, 14)); // NOI18N
        jLabel1.setText("Role");

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Microsoft New Tai Lue", 3, 14)); // NOI18N
        jLabel2.setText("Username");

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Microsoft New Tai Lue", 3, 14)); // NOI18N
        jLabel3.setText("Password");

        btnLogin.setBackground(new java.awt.Color(204, 204, 255));
        btnLogin.setFont(new java.awt.Font("Microsoft New Tai Lue", 2, 14)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(0, 0, 102));
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        cmbRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None" }));
        cmbRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbRoleActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(204, 255, 255));
        jLabel4.setFont(new java.awt.Font("Microsoft New Tai Lue", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 255, 255));
        jLabel4.setText("System Role Login");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(238, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(27, 27, 27)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cmbRole, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnLogin)
                                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(250, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel4)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtUsername)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnLogin)
                .addContainerGap(383, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        if (admin.validatePassword(txtUsername.getText() ,txtPassword.getText())!=null){
            if (role.equals("Brokerage Manager")){
                BrokerageManager bm = new BrokerageManager(userProcessContainer, admin,txtUsername.getText());
                userProcessContainer.add("BrokerageManager", bm);
                CardLayout layout = (CardLayout)userProcessContainer.getLayout();
                layout.next(userProcessContainer);
            }
            if (role.equals("Exchange Administrator")){
                ExchangeAdministrator ea = new ExchangeAdministrator(userProcessContainer, admin,txtUsername.getText());
                userProcessContainer.add("ExchangeAdministrator", ea);
                CardLayout layout = (CardLayout)userProcessContainer.getLayout();
                layout.next(userProcessContainer);
            }
            if (role.equals("Compliance Oﬃcer")){
                ComplianceOfficer co = new ComplianceOfficer(userProcessContainer, admin,txtUsername.getText());
                userProcessContainer.add("ComplianceOfficer", co);
                CardLayout layout = (CardLayout)userProcessContainer.getLayout();
                layout.next(userProcessContainer);
            }
//            if (role.equals("Financial Advisor")){
//                //FinancialAdvisor fa = new FinancialAdvisor(userProcessContainer, admin,txtUsername.getText());
//                FinancialAdvisor fa = new FinancialAdvisor(userProcessContainer, admin,txtUsername.getText());
//                userProcessContainer.add("FinancialAdvisor", fa);
//                CardLayout layout = (CardLayout)userProcessContainer.getLayout();
//                layout.next(userProcessContainer);
//            }
            if (role.equals("Customer Support Agent")){
                CustomerSupportDashboard csa = new CustomerSupportDashboard(userProcessContainer, admin,txtUsername.getText());
                userProcessContainer.add("CustomerSupportDashboard", csa);
                CardLayout layout = (CardLayout)userProcessContainer.getLayout();
                layout.next(userProcessContainer);
            }
            if (role.equals("Risk Analyst")){
                try {
                    RiskAnalyst ra = new RiskAnalyst(userProcessContainer,admin,txtUsername.getText(), txtPassword.getText());
                    userProcessContainer.add("RiskAnalyst", ra);
                    CardLayout layout = (CardLayout)userProcessContainer.getLayout();
                    layout.next(userProcessContainer);
                } catch (IOException ex) {
                    Logger.getLogger(RoleLogin.class.getName()).log(Level.SEVERE, null, ex);
                } catch (InterruptedException ex) {
                    Logger.getLogger(RoleLogin.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        else
            JOptionPane.showMessageDialog(this, "Sign in failed!");
    }//GEN-LAST:event_btnLoginActionPerformed

    private void cmbRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbRoleActionPerformed
        // TODO add your handling code here:
        role = cmbRole.getSelectedItem().toString();
    }//GEN-LAST:event_cmbRoleActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JComboBox<String> cmbRole;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
