package ui.Admin;

import enterprise.Bodies.Enterprise;
import enterprise.Bodies.EnterpriseDirectory;
import java.awt.CardLayout;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import model.OrderItem;
import model.Person;
import enterprise.StockExchange.Stock;
import model.Order;
/**
 *
 * @author  rohanjauhari
 */
public class Admin extends javax.swing.JPanel {

  
    private JPanel userProcessContainer;
    Order currentOrder, sellingOrder;
    PersonDirectory personDirectory;
    private static PasswordDirectory passwords;
    EnterpriseDirectory enterpriseDirectory;
    HashMap<Person, String> messageToCST=new HashMap<>();
    HashMap<Person, String>  messageToEA=new HashMap<>();
    String messageToSEbyBF,messageToSEbyIAF,messageToSEbyRB, messageToCSObyAT,messageToCSObyCT,messageToCSObyITD,messageToCSObyRMT;
    HashMap<Person, Order> traderBuyingOrder=new HashMap<>();
    HashMap<Person, Order> traderSellingOrder=new HashMap<>();
    public Admin(JPanel userProcessContainer, PasswordDirectory pd, PersonDirectory personDirectory,EnterpriseDirectory enterpriseDirectory) {
        passwords = pd;
//        traderBuyingOrder = new HashMap<>();
//        traderSellingOrder = new HashMap<>();
//        messageToCST=new HashMap<>();
//        messageToEA=new HashMap<>();
        this.personDirectory=personDirectory;
        initComponents();
        this.enterpriseDirectory = enterpriseDirectory;
        populateTable();
        
        this.userProcessContainer=userProcessContainer;
    }
      public Person validatePassword(String text, String text0, String role) {

          if( passwords.validatePassword(text, text0))
              return personDirectory.findPerson(text);
          return null;
    }

    public Person register(String text, String text0, String role) {
        if( !passwords.register(text, text0))
                    return null;
        Person p = new Person(text, role);
        
        personDirectory.newPerson(p);
        

         return p;
    }
    public void deRegister(Person p){
        personDirectory.selfDelete(p);
    }
    
    public void sendMessageToCST(Person p, String message){
        messageToCST.put(p, message);
    }
    
    public void sendMessageToEA(Person p, String message){
        messageToEA.put(p, message);
    }
    
    public void sendMessageToSEbyBF( String text) {
        messageToSEbyBF=text;
    }
    
    public void sendMessageToSEbyIAF( String text) {
        messageToSEbyIAF=text;
    }
    
    
    public void sendMessageToSEbyRB( String text) {
        messageToSEbyRB=text;
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnCreateEnterprise = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblEnterprise = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 255));
        setPreferredSize(new java.awt.Dimension(650, 600));

        jLabel1.setBackground(new java.awt.Color(204, 204, 255));
        jLabel1.setFont(new java.awt.Font("Optima", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Welcome Admin!");

        jLabel2.setFont(new java.awt.Font("Optima", 3, 14)); // NOI18N
        jLabel2.setText("Here are the accounts");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Username", "Password", "Role", "Enterprise", "Organization", "Designation"
            }
        ));
        jTable1.setEnabled(false);
        jScrollPane1.setViewportView(jTable1);

        jButton1.setBackground(new java.awt.Color(204, 204, 255));
        jButton1.setFont(new java.awt.Font("Optima", 1, 12)); // NOI18N
        jButton1.setText("Delete");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(51, 51, 51));
        jButton2.setForeground(new java.awt.Color(204, 204, 204));
        jButton2.setText("<");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btnCreateEnterprise.setBackground(new java.awt.Color(204, 204, 255));
        btnCreateEnterprise.setFont(new java.awt.Font("Optima", 1, 12)); // NOI18N
        btnCreateEnterprise.setText("Create Enterprise");
        btnCreateEnterprise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateEnterpriseActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Optima", 3, 14)); // NOI18N
        jLabel3.setText("Here are the Enterprises");

        tblEnterprise.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Enterprise name", "Enterprise admin", "admin password", "Enterprise Role"
            }
        ));
        tblEnterprise.setEnabled(false);
        jScrollPane2.setViewportView(tblEnterprise);

        jButton3.setBackground(new java.awt.Color(204, 204, 255));
        jButton3.setFont(new java.awt.Font("Optima", 1, 12)); // NOI18N
        jButton3.setText("Edit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(204, 204, 255));
        jButton4.setFont(new java.awt.Font("Optima", 1, 12)); // NOI18N
        jButton4.setText("Save");
        jButton4.setEnabled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(204, 204, 255));
        jButton5.setFont(new java.awt.Font("Optima", 1, 12)); // NOI18N
        jButton5.setText("Edit");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        btnSave.setBackground(new java.awt.Color(204, 204, 255));
        btnSave.setFont(new java.awt.Font("Optima", 1, 12)); // NOI18N
        btnSave.setText("Save");
        btnSave.setEnabled(false);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(204, 204, 255));
        jButton7.setFont(new java.awt.Font("Optima", 1, 12)); // NOI18N
        jButton7.setText("Delete");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addContainerGap(25, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addContainerGap(317, Short.MAX_VALUE)
                                    .addComponent(jButton3)
                                    .addGap(20, 20, 20)
                                    .addComponent(jButton4)
                                    .addGap(20, 20, 20)
                                    .addComponent(jButton1))
                                .addGroup(layout.createSequentialGroup()
                                    .addContainerGap(317, Short.MAX_VALUE)
                                    .addComponent(jButton5)
                                    .addGap(20, 20, 20)
                                    .addComponent(btnSave)
                                    .addGap(20, 20, 20)
                                    .addComponent(jButton7)))
                            .addGap(0, 0, Short.MAX_VALUE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(77, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCreateEnterprise)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jButton2)
                .addGap(0, 0, 0)
                .addComponent(jLabel1)
                .addGap(62, 62, 62)
                .addComponent(btnCreateEnterprise)
                .addGap(34, 34, 34)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(btnSave)
                    .addComponent(jButton7))
                .addGap(100, 100, 100)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addGap(21, 21, 21))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = jTable1.getSelectedRow() ;
        if (selectedRowIndex < 0) {
            JOptionPane.showMessageDialog(this, "Please select the order item first.");
            return;
        }
        Person p = (Person) jTable1.getValueAt(selectedRowIndex, 0);
        deRegister(p);
        populateTable();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this) ;
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout. previous (userProcessContainer);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    
    private void btnCreateEnterpriseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateEnterpriseActionPerformed
        // TODO add your handling code here:
        CreateEnterprise ce = new CreateEnterprise(userProcessContainer,enterpriseDirectory,passwords ,personDirectory, this);
        userProcessContainer.add("CreateEnterprise",ce);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnCreateEnterpriseActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        jTable1.setEnabled(true);
        jButton4.setEnabled(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = jTable1.getSelectedRow() ;
        if (selectedRowIndex < 0) {
            JOptionPane.showMessageDialog(this, "Please select the order item first.");
            return;
        }
        Person p = (Person) jTable1.getValueAt(selectedRowIndex, 0);
        p.setUsername(jTable1.getValueAt(selectedRowIndex, 0).toString());
        p.setPassword(jTable1.getValueAt(selectedRowIndex, 1).toString());
        p.setRole(jTable1.getValueAt(selectedRowIndex, 2).toString());
        p.setEnterpriseName(jTable1.getValueAt(selectedRowIndex, 3).toString());
        p.setOrgName(jTable1.getValueAt(selectedRowIndex, 4).toString());
        p.setDesignation(jTable1.getValueAt(selectedRowIndex, 5).toString());
        JOptionPane.showMessageDialog(this, "Save successful");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        tblEnterprise.setEnabled(true);
        btnSave.setEnabled(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = tblEnterprise.getSelectedRow() ;
        if (selectedRowIndex < 0) {
            JOptionPane.showMessageDialog(this, "Please select the order item first.");
            return;
        }
        Enterprise e = (Enterprise) tblEnterprise.getValueAt(selectedRowIndex, 0);
        deRegister(e.getPerson());
        e.setName(tblEnterprise.getValueAt(selectedRowIndex, 0).toString());
        e.setUsername(tblEnterprise.getValueAt(selectedRowIndex, 1).toString());
        e.setPassword(tblEnterprise.getValueAt(selectedRowIndex, 2).toString());
        e.setRole(tblEnterprise.getValueAt(selectedRowIndex, 3).toString());
        Person p = register(tblEnterprise.getValueAt(selectedRowIndex, 1).toString(), tblEnterprise.getValueAt(selectedRowIndex, 2).toString(), tblEnterprise.getValueAt(selectedRowIndex, 3).toString());
            p.setEnterpriseName(e.getName());
            p.setDesignation("Enterprise Admin.");
            p.setOrgName("N/A");
            populateTable();
        JOptionPane.showMessageDialog(this, "Update Successful");
    }//GEN-LAST:event_btnSaveActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = tblEnterprise.getSelectedRow() ;
        if (selectedRowIndex < 0) {
            JOptionPane.showMessageDialog(this, "Please select the order item first.");
            return;
        }
        Enterprise e = (Enterprise) tblEnterprise.getValueAt(selectedRowIndex, 0);
        enterpriseDirectory.remove(e);
        deRegister(personDirectory.findPerson(e.getUsername()));
        populateTable();
        JOptionPane.showMessageDialog(this, "Delete Successful");
    }//GEN-LAST:event_jButton7ActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateEnterprise;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tblEnterprise;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        
        for (Person p: personDirectory.getPersons()) {
            Object row[] = new Object [6];
            row [0] = p;
            row [1] = passwords.getPasswords().get(p.getUsername()) ;
            row[2] = p.getRole();
            row[3] = p.getEnterpriseName();
            row[4] = p.getOrgName();
            row[5] = p.getDesignation();
            model. addRow (row);
    }
 
    DefaultTableModel model1 = (DefaultTableModel) tblEnterprise.getModel();
    model1.setRowCount(0);
    for (Enterprise e: enterpriseDirectory.getEnterprices()) {
        Object row[] = new Object [4];
        row [0] = e;
        row [1] = e.getUsername() ;
        row[3] = e.getRole();
        row[2] = e.getPassword();
        model1. addRow (row);
}
    }

    public void updatePassword(String username, String password) {
        passwords.update(username,password);
    }

    public void setSellingRecord(Person p, Order currentOrder) {
        traderSellingOrder.put(p, currentOrder);
    }
    
    public HashMap<Person, Order> getSellingRecord(){
        return traderSellingOrder;
    }
    
    public HashMap<Person, Order> getBuyingRecord(){
        return traderBuyingOrder;
    }
        
    public void setBuyingRecord(Person p, Order currentOrder){
        traderSellingOrder.put(p, currentOrder);
    }

    public void sendMessageToCSObyAT(String text) {
        messageToCSObyAT = text;
    }

    public void sendMessageToCSObyCT(String text) {
        messageToCSObyCT = text;
    }
    
        public void sendMessageToCSObyITD(String text) {
        messageToCSObyITD = text;
    }
        
            public void sendMessageToCSObyRMT(String text) {
        messageToCSObyRMT = text;
    }

    public void setAuditChecks(HashMap<String, Boolean> auditChecks) {
        System.out.println(auditChecks);
    }
    
}
